name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    permissions:
        pages: write
        id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "21.x"
      - run: npm install
      - run: git config --global user.email "amoo.hashem.mehraban@gmail.com"
      - run: git config --global user.name "Seyed Alireza Hashemi"
      - run: npm run deploy